config:
  message: Hello From Dev Spring Config Server
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
